title: rOpenSci Screencasts
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
github:
  videos_url: https://vimeo.com/channels/roscreencasts
  repository_url: https://github.com/ropensci/screencasts
