markdown: redcarpet
highlighter: pygments
permalink: /:title/
# baseurl:   /screencasts
# url: 			 "https://ropensci.github.io"
twitter_username: ropensci
github_username:  ropensci

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
