title: 				rOpenSci Screencasts
permalink:    /:title/
baseurl:    	/screencasts/
url: 				 "http://ropensci.github.io"
author:
  name:       'Scott Chamberlain'
  email:      'myrmecocystus@gmail.com'
email: 			 info@ropensci.org
description: "rOpenSci Screencasts"
twitter_username: ropensci
github_username:  ropensci
description: ropensci screencasts

# Build settings
markdown: rdiscount
highlighter: pygments
