markdown: redcarpet
highlighter: null
permalink: /:title/
baseurl:   /screencasts
url: 			 "http://ropensci.github.io"
twitter_username: ropensci
github_username:  ropensci

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
